version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
  
  nodeapp:
    build: ./app1
    volumes : 
      - ./app1:/home/dockerapp/chat1
      - /home/dockerapp/chat1/node_modules
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
    # expose:
    #   - '8080'
    restart: always    